//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZaharWpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChapterTexts
    {
        public int TextID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public string Text { get; set; }
    
        public virtual Chapters Chapters { get; set; }
    }
}
