//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZaharWpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapters
    {
        public Chapters()
        {
            this.ChapterTexts = new HashSet<ChapterTexts>();
        }
    
        public int ChapterID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ChapterNumber { get; set; }
        public string Title { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual ICollection<ChapterTexts> ChapterTexts { get; set; }
    }
}
