//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZaharWpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammingLanguages
    {
        public ProgrammingLanguages()
        {
            this.Books = new HashSet<Books>();
            this.Solutions = new HashSet<Solutions>();
            this.Users = new HashSet<Users>();
        }
    
        public int LanguageID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Books> Books { get; set; }
        public virtual ICollection<Solutions> Solutions { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
