//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZaharWpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solutions
    {
        public int SolutionID { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<int> LanguageID { get; set; }
    
        public virtual ProgrammingLanguages ProgrammingLanguages { get; set; }
    }
}
